# Generated by Django 2.1.5 on 2019-01-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(max_length=155, upload_to='media/mems/%Y/%m/%d')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the meme')),
                ('views', models.IntegerField(default=0, verbose_name='Number of views')),
                ('rating', models.FloatField(default=0.5, verbose_name='rating of a meme, from 0 to 1')),
                ('language', models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], max_length=10, verbose_name='language of a meme')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of a tag')),
            ],
        ),
        migrations.AddField(
            model_name='meme',
            name='tags',
            field=models.ManyToManyField(to='memes_app.Tag', verbose_name='tags relation'),
        ),
    ]
