# Generated by Django 2.1.5 on 2019-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(height_field='pic_height', max_length=155, upload_to='media/mems/%Y/%m/%d', width_field='pic_width')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
            ],
        ),
    ]
