# Generated by Django 2.1.5 on 2019-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='pic',
            field=models.ImageField(max_length=155, upload_to='media/memes/%Y/%m/%d'),
        ),
    ]
